//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abc.Nes.Xades.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Abc.Nes.Xades.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciąg nie może być pusty ani zerowy..
        /// </summary>
        internal static string Arg_EmptyOrNullString {
            get {
                return ResourceManager.GetString("Arg_EmptyOrNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks był poza zakresem. Musi być nieujemna i mniejsza niż wielkość kolekcji..
        /// </summary>
        internal static string ArgumentOutOfRange_Index {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można zbudować łańcucha certyfikatów w zaufanym urzędzie głównym..
        /// </summary>
        internal static string Cryptography_Partial_Chain {
            get {
                return ResourceManager.GetString("Cryptography_Partial_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zły rozmiar opakowanego klucza..
        /// </summary>
        internal static string Cryptography_Xml_BadWrappedKeySize {
            get {
                return ResourceManager.GetString("Cryptography_Xml_BadWrappedKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Cipher Data powinien mieć element CipherValue lub CipherReference..
        /// </summary>
        internal static string Cryptography_Xml_CipherValueElementRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_CipherValueElementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się utworzyć klucza podpisu..
        /// </summary>
        internal static string Cryptography_Xml_CreatedKeyFailed {
            get {
                return ResourceManager.GetString("Cryptography_Xml_CreatedKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można utworzyć obiektu algorytmu skrótu..
        /// </summary>
        internal static string Cryptography_Xml_CreateHashAlgorithmFailed {
            get {
                return ResourceManager.GetString("Cryptography_Xml_CreateHashAlgorithmFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można utworzyć transformacji XML identyfikowanej przez identyfikator URI {0}..
        /// </summary>
        internal static string Cryptography_Xml_CreateTransformFailed {
            get {
                return ResourceManager.GetString("Cryptography_Xml_CreateTransformFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przed wygenerowaniem kodu XML należy określić DigestMethod w referencji..
        /// </summary>
        internal static string Cryptography_Xml_DigestMethodRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_DigestMethodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencja musi zawierać DigestValue..
        /// </summary>
        internal static string Cryptography_Xml_DigestValueRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_DigestValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontekst XmlDocument jest wymagany dla przekształceń otoczonych..
        /// </summary>
        internal static string Cryptography_Xml_EnvelopedSignatureRequiresContext {
            get {
                return ResourceManager.GetString("Cryptography_Xml_EnvelopedSignatureRequiresContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ obiektu wejściowego jest nieprawidłowy..
        /// </summary>
        internal static string Cryptography_Xml_IncorrectObjectType {
            get {
                return ResourceManager.GetString("Cryptography_Xml_IncorrectObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zniekształcony element {0}..
        /// </summary>
        internal static string Cryptography_Xml_InvalidElement {
            get {
                return ResourceManager.GetString("Cryptography_Xml_InvalidElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zniekształcony element właściwości szyfrowania..
        /// </summary>
        internal static string Cryptography_Xml_InvalidEncryptionProperty {
            get {
                return ResourceManager.GetString("Cryptography_Xml_InvalidEncryptionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmiar klucza powinien być nieujemną liczbą całkowitą..
        /// </summary>
        internal static string Cryptography_Xml_InvalidKeySize {
            get {
                return ResourceManager.GetString("Cryptography_Xml_InvalidKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zniekształcony element referencyjny..
        /// </summary>
        internal static string Cryptography_Xml_InvalidReference {
            get {
                return ResourceManager.GetString("Cryptography_Xml_InvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość podpisu z adresem MAC powinna być mniejsza niż długość wyjściowa skrótu..
        /// </summary>
        internal static string Cryptography_Xml_InvalidSignatureLength {
            get {
                return ResourceManager.GetString("Cryptography_Xml_InvalidSignatureLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość w bitach podpisu z adresem MAC powinna być wielokrotnością 8..
        /// </summary>
        internal static string Cryptography_Xml_InvalidSignatureLength2 {
            get {
                return ResourceManager.GetString("Cryptography_Xml_InvalidSignatureLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer seryjny wydawcy X509 jest nieprawidłowy..
        /// </summary>
        internal static string Cryptography_Xml_InvalidX509IssuerSerialNumber {
            get {
                return ResourceManager.GetString("Cryptography_Xml_InvalidX509IssuerSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do sprawdzenia podpisu wymagany jest element KeyInfo..
        /// </summary>
        internal static string Cryptography_Xml_KeyInfoRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_KeyInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość zaszyfrowanych danych w zawijaniu klucza wynosi 32, 40 lub 48 bajtów..
        /// </summary>
        internal static string Cryptography_Xml_KW_BadKeySize {
            get {
                return ResourceManager.GetString("Cryptography_Xml_KW_BadKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz podpisu nie został załadowany..
        /// </summary>
        internal static string Cryptography_Xml_LoadKeyFailed {
            get {
                return ResourceManager.GetString("Cryptography_Xml_LoadKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie określono algorytmu symetrycznego..
        /// </summary>
        internal static string Cryptography_Xml_MissingAlgorithm {
            get {
                return ResourceManager.GetString("Cryptography_Xml_MissingAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie określono danych szyfrowania..
        /// </summary>
        internal static string Cryptography_Xml_MissingCipherData {
            get {
                return ResourceManager.GetString("Cryptography_Xml_MissingCipherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można pobrać klucza odszyfrowywania..
        /// </summary>
        internal static string Cryptography_Xml_MissingDecryptionKey {
            get {
                return ResourceManager.GetString("Cryptography_Xml_MissingDecryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można pobrać klucza szyfrowania..
        /// </summary>
        internal static string Cryptography_Xml_MissingEncryptionKey {
            get {
                return ResourceManager.GetString("Cryptography_Xml_MissingEncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Określona transformacja kryptograficzna nie jest obsługiwana..
        /// </summary>
        internal static string Cryptography_Xml_NotSupportedCryptographicTransform {
            get {
                return ResourceManager.GetString("Cryptography_Xml_NotSupportedCryptographicTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagany jest co najmniej jeden element Reference..
        /// </summary>
        internal static string Cryptography_Xml_ReferenceElementRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_ReferenceElementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ odwołania musi być ustawiony w obiekcie EncryptedReference..
        /// </summary>
        internal static string Cryptography_Xml_ReferenceTypeRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_ReferenceTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby rozpoznać identyfikator Uri odwołania {0}, wymagany jest kontekst XmlDocument..
        /// </summary>
        internal static string Cryptography_Xml_SelfReferenceRequiresContext {
            get {
                return ResourceManager.GetString("Cryptography_Xml_SelfReferenceRequiresContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można utworzyć SignatureDescription dla podanego algorytmu podpisu..
        /// </summary>
        internal static string Cryptography_Xml_SignatureDescriptionNotCreated {
            get {
                return ResourceManager.GetString("Cryptography_Xml_SignatureDescriptionNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz nie pasuje do SignatureMethod..
        /// </summary>
        internal static string Cryptography_Xml_SignatureMethodKeyMismatch {
            get {
                return ResourceManager.GetString("Cryptography_Xml_SignatureMethodKeyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagana jest metoda podpisu..
        /// </summary>
        internal static string Cryptography_Xml_SignatureMethodRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_SignatureMethodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpis wymaga wartości SignatureValue..
        /// </summary>
        internal static string Cryptography_Xml_SignatureValueRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_SignatureValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpis wymaga SignedInfo..
        /// </summary>
        internal static string Cryptography_Xml_SignedInfoRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_SignedInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ danych wejściowych był nieprawidłowy dla tej transformacji..
        /// </summary>
        internal static string Cryptography_Xml_TransformIncorrectInputType {
            get {
                return ResourceManager.GetString("Cryptography_Xml_TransformIncorrectInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napotkano nieznaną transformację..
        /// </summary>
        internal static string Cryptography_Xml_UnknownTransform {
            get {
                return ResourceManager.GetString("Cryptography_Xml_UnknownTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można rozpoznać ścieżki Uri {0}..
        /// </summary>
        internal static string Cryptography_Xml_UriNotResolved {
            get {
                return ResourceManager.GetString("Cryptography_Xml_UriNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany identyfikator Uri nie jest obsługiwany..
        /// </summary>
        internal static string Cryptography_Xml_UriNotSupported {
            get {
                return ResourceManager.GetString("Cryptography_Xml_UriNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dla elementu CipherReference wymagany jest atrybut Uri..
        /// </summary>
        internal static string Cryptography_Xml_UriRequired {
            get {
                return ResourceManager.GetString("Cryptography_Xml_UriRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napotkano null Context..
        /// </summary>
        internal static string Cryptography_Xml_XrmlMissingContext {
            get {
                return ResourceManager.GetString("Cryptography_Xml_XrmlMissingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRelDecryptor jest wymagany..
        /// </summary>
        internal static string Cryptography_Xml_XrmlMissingIRelDecryptor {
            get {
                return ResourceManager.GetString("Cryptography_Xml_XrmlMissingIRelDecryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Węzeł wystawcy jest wymagany..
        /// </summary>
        internal static string Cryptography_Xml_XrmlMissingIssuer {
            get {
                return ResourceManager.GetString("Cryptography_Xml_XrmlMissingIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagany jest węzeł licencji..
        /// </summary>
        internal static string Cryptography_Xml_XrmlMissingLicence {
            get {
                return ResourceManager.GetString("Cryptography_Xml_XrmlMissingLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można odszyfrować treści grantu..
        /// </summary>
        internal static string Cryptography_Xml_XrmlUnableToDecryptGrant {
            get {
                return ResourceManager.GetString("Cryptography_Xml_XrmlUnableToDecryptGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualna wartość skrótu: {0}.
        /// </summary>
        internal static string Log_ActualHashValue {
            get {
                return ResourceManager.GetString("Log_ActualHashValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczynanie konwersji kanonicznej za pomocą „{0}” ({1})..
        /// </summary>
        internal static string Log_BeginCanonicalization {
            get {
                return ResourceManager.GetString("Log_BeginCanonicalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęcie obliczania podpisu..
        /// </summary>
        internal static string Log_BeginSignatureComputation {
            get {
                return ResourceManager.GetString("Log_BeginSignatureComputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęcie weryfikacji podpisu..
        /// </summary>
        internal static string Log_BeginSignatureVerification {
            get {
                return ResourceManager.GetString("Log_BeginSignatureVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie i weryfikowanie łańcucha X509 dla certyfikatu {0}..
        /// </summary>
        internal static string Log_BuildX509Chain {
            get {
                return ResourceManager.GetString("Log_BuildX509Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canonicalization transform is using resolver {0} and base URI &quot;{1}&quot;..
        /// </summary>
        internal static string Log_CanonicalizationSettings {
            get {
                return ResourceManager.GetString("Log_CanonicalizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output of canonicalization transform: {0}.
        /// </summary>
        internal static string Log_CanonicalizedOutput {
            get {
                return ResourceManager.GetString("Log_CanonicalizedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate chain:.
        /// </summary>
        internal static string Log_CertificateChain {
            get {
                return ResourceManager.GetString("Log_CertificateChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking signature format using format validator &quot;[{0}] {1}.{2}&quot;..
        /// </summary>
        internal static string Log_CheckSignatureFormat {
            get {
                return ResourceManager.GetString("Log_CheckSignatureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking signature on SignedInfo with id &quot;{0}&quot;..
        /// </summary>
        internal static string Log_CheckSignedInfo {
            get {
                return ResourceManager.GetString("Log_CheckSignedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature format validation failed..
        /// </summary>
        internal static string Log_FormatValidationNotSuccessful {
            get {
                return ResourceManager.GetString("Log_FormatValidationNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature format validation was successful..
        /// </summary>
        internal static string Log_FormatValidationSuccessful {
            get {
                return ResourceManager.GetString("Log_FormatValidationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found key usages &quot;{0}&quot; in extension {1} on certificate {2}..
        /// </summary>
        internal static string Log_KeyUsages {
            get {
                return ResourceManager.GetString("Log_KeyUsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No namespaces are being propagated..
        /// </summary>
        internal static string Log_NoNamespacesPropagated {
            get {
                return ResourceManager.GetString("Log_NoNamespacesPropagated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propagating namespace {0}=&quot;{1}&quot;..
        /// </summary>
        internal static string Log_PropagatingNamespace {
            get {
                return ResourceManager.GetString("Log_PropagatingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw signature: {0}.
        /// </summary>
        internal static string Log_RawSignatureValue {
            get {
                return ResourceManager.GetString("Log_RawSignatureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference {0} hashed with &quot;{1}&quot; ({2}) has hash value {3}, expected hash value {4}..
        /// </summary>
        internal static string Log_ReferenceHash {
            get {
                return ResourceManager.GetString("Log_ReferenceHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revocation flag for chain building: {0}..
        /// </summary>
        internal static string Log_RevocationFlag {
            get {
                return ResourceManager.GetString("Log_RevocationFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revocation mode for chain building: {0}..
        /// </summary>
        internal static string Log_RevocationMode {
            get {
                return ResourceManager.GetString("Log_RevocationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed xml recursion limit hit while trying to decrypt the key. Reference {0} hashed with &quot;{1}&quot; and ({2})..
        /// </summary>
        internal static string Log_SignedXmlRecursionLimit {
            get {
                return ResourceManager.GetString("Log_SignedXmlRecursionLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating signature with key {0} using signature description {1}, hash algorithm {2}, and asymmetric signature formatter {3}..
        /// </summary>
        internal static string Log_SigningAsymmetric {
            get {
                return ResourceManager.GetString("Log_SigningAsymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating signature using keyed hash algorithm {0}..
        /// </summary>
        internal static string Log_SigningHmac {
            get {
                return ResourceManager.GetString("Log_SigningHmac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing reference {0}, Uri &quot;{1}&quot;, Id &quot;{2}&quot;, Type &quot;{3}&quot; with hash algorithm &quot;{4}&quot; ({5})..
        /// </summary>
        internal static string Log_SigningReference {
            get {
                return ResourceManager.GetString("Log_SigningReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformed reference contents: {0}.
        /// </summary>
        internal static string Log_TransformedReferenceContents {
            get {
                return ResourceManager.GetString("Log_TransformedReferenceContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canonicalization method &quot;{0}&quot; is not on the safe list. Safe canonicalization methods are: {1}..
        /// </summary>
        internal static string Log_UnsafeCanonicalizationMethod {
            get {
                return ResourceManager.GetString("Log_UnsafeCanonicalizationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform method &quot;{0}&quot; is not on the safe list. Safe transform methods are: {1}..
        /// </summary>
        internal static string Log_UnsafeTransformMethod {
            get {
                return ResourceManager.GetString("Log_UnsafeTransformMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL retrieval timeout for chain building: {0}..
        /// </summary>
        internal static string Log_UrlTimeout {
            get {
                return ResourceManager.GetString("Log_UrlTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification failed checking {0}..
        /// </summary>
        internal static string Log_VerificationFailed {
            get {
                return ResourceManager.GetString("Log_VerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to references.
        /// </summary>
        internal static string Log_VerificationFailed_References {
            get {
                return ResourceManager.GetString("Log_VerificationFailed_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignedInfo.
        /// </summary>
        internal static string Log_VerificationFailed_SignedInfo {
            get {
                return ResourceManager.GetString("Log_VerificationFailed_SignedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X509 chain verification.
        /// </summary>
        internal static string Log_VerificationFailed_X509Chain {
            get {
                return ResourceManager.GetString("Log_VerificationFailed_X509Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X509 key usage verification.
        /// </summary>
        internal static string Log_VerificationFailed_X509KeyUsage {
            get {
                return ResourceManager.GetString("Log_VerificationFailed_X509KeyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification flags for chain building: {0}..
        /// </summary>
        internal static string Log_VerificationFlag {
            get {
                return ResourceManager.GetString("Log_VerificationFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification time for chain building: {0}..
        /// </summary>
        internal static string Log_VerificationTime {
            get {
                return ResourceManager.GetString("Log_VerificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification with key {0} was not successful..
        /// </summary>
        internal static string Log_VerificationWithKeyNotSuccessful {
            get {
                return ResourceManager.GetString("Log_VerificationWithKeyNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification with key {0} was successful..
        /// </summary>
        internal static string Log_VerificationWithKeySuccessful {
            get {
                return ResourceManager.GetString("Log_VerificationWithKeySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing reference {0}, Uri &quot;{1}&quot;, Id &quot;{2}&quot;, Type &quot;{3}&quot;..
        /// </summary>
        internal static string Log_VerifyReference {
            get {
                return ResourceManager.GetString("Log_VerifyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying SignedInfo using key {0}, signature description {1}, hash algorithm {2}, and asymmetric signature deformatter {3}..
        /// </summary>
        internal static string Log_VerifySignedInfoAsymmetric {
            get {
                return ResourceManager.GetString("Log_VerifySignedInfoAsymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying SignedInfo using keyed hash algorithm {0}..
        /// </summary>
        internal static string Log_VerifySignedInfoHmac {
            get {
                return ResourceManager.GetString("Log_VerifySignedInfoHmac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error building X509 chain: {0}: {1}..
        /// </summary>
        internal static string Log_X509ChainError {
            get {
                return ResourceManager.GetString("Log_X509ChainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using context: {0}.
        /// </summary>
        internal static string Log_XmlContext {
            get {
                return ResourceManager.GetString("Log_XmlContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorytm klucza certyfikatu nie jest obsługiwany..
        /// </summary>
        internal static string NotSupported_KeyAlgorithm {
            get {
                return ResourceManager.GetString("NotSupported_KeyAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Security.Cryptography.Xml nie jest obsługiwany na tej platformie..
        /// </summary>
        internal static string SystemSecurityCryptographyXml_PlatformNotSupported {
            get {
                return ResourceManager.GetString("SystemSecurityCryptographyXml_PlatformNotSupported", resourceCulture);
            }
        }
    }
}
